Hw 1
ISkalchenkov/AdvCpp.2020 pull request #1
Opened 2020-03-20 15:52 UTC by ISkalchenkov

2020-03-23 21:16 UTC, smirnov-vs requested changes
Тебе надо проработать систему передачи ошибок из библиотеки, 2 лекция уже прошла и сильно в этом поможет

2020-03-23 21:16 UTC, smirnov-vs commented on hw-1/lib/Process.h
> +namespace proc{
цепляет глаз кавычка

2020-03-23 21:16 UTC, smirnov-vs commented on hw-1/lib/Process.h
> +    int c2p_pipefd[2];
классу достаточно хранить только 2 дескриптора

2020-03-23 21:16 UTC, smirnov-vs commented on hw-1/src/Process.cpp
> +        exit(EXIT_FAILURE);
как же так, конструктор библиотеки убьет мою программу?

2020-03-23 21:16 UTC, smirnov-vs commented on hw-1/src/Process.cpp
> +        perror("Pipe error");
библиотеки с консолью не общаются

2020-03-23 21:16 UTC, smirnov-vs commented on hw-1/src/Process.cpp
> +void Process::close() {
этот метод закрывает вообще весь процесс

2020-03-23 21:16 UTC, smirnov-vs commented on hw-1/src/main.cpp
> +    std::string path = "./echo";
у меня вот нет в папке такой штуки, как мне пользоваться этим тестом?

2020-03-23 21:16 UTC, smirnov-vs commented on hw-1/src/main.cpp
> +    memset(buf, '\0', sizeof(buf));
сверху юзаешь string, почему бы не читать тоже в стринг?

2020-04-01 18:09 UTC, ISkalchenkov commented
Здравствуйте, замечания исправлены. Извиняюсь за позднее отправление

2020-04-05 14:14 UTC, smirnov-vs approved these changes
Привет!
Задачу закрываю так как прошли сроки

2020-04-05 14:14 UTC, smirnov-vs commented on hw-1/src/main.cpp
> +        process.readExact(&buf[0], hello.size());
`buf.data()`

2020-04-05 14:14 UTC, smirnov-vs commented on hw-1/src/Process.cpp
> +        std::cerr << err.what() << std::endl;
это будет мешать пользовательскому логу

2020-04-05 14:14 UTC, smirnov-vs commented on hw-1/src/Process.cpp
> +            throw ProcessError();
непонятно, ошибка произошла здесь или где то еще

2020-04-08 23:59 UTC, merged