Hw-2
ISkalchenkov/AdvCpp.2020 pull request #2
Opened 2020-04-13 03:08 UTC by ISkalchenkov

2020-04-18 08:58 UTC, a-badin requested changes

2020-04-18 08:58 UTC, a-badin commented on hw-2/CMakeLists.txt
> +include_directories(include)
Давайте потренируемся пользоваться хорошими практиками cmake, воспользуйтесь target_include_directories из лекции 1

2020-04-18 08:58 UTC, a-badin commented on hw-2/include/FileLogger.hpp
> +    FileLogger(const FileLogger& rhs) = delete;
Методы копирования и переноса сделает за вас компилятор

2020-04-18 08:58 UTC, a-badin commented on hw-2/include/FileLogger.hpp
> +    FileLogger(FileLogger&& rhs) = delete;
Вот это очень строгое ограничение. Теперь с FileLogger нельзя сделать практически ничего, ни передать, ни положить в контейнер.
Чем оправдано такое ограничение?

2020-04-18 08:58 UTC, a-badin commented on hw-2/src/Logger.cpp
> +    if (logger) {
Игнорировать тоже не очень хорошо, явное поведение лучше неявного.
Киньте исключение, если пользователю захочется игнорировать такую ошибку, он просто поймает и не будет реагировать на ваше исключение

2020-04-18 08:58 UTC, a-badin commented on hw-2/src/LogModifier.cpp
> +std::string LogModifier::formate(const std::string msg, Level lvl) noexcept {
format

2020-04-18 08:58 UTC, a-badin commented on hw-2/include/LogModifier.hpp
> +    static LogModifier& get_instance() noexcept;
На самом деле Singleton является антипаттерном проектирования. Есть довольно небольшое число случаев, когда удобство от его применения перевешивают его минусы.
Если я хочу сделать 2 логгера, Stdout logger и FileLogger, вполне лочичным звучит сценарий при котором для одного логгера я хочу иметь один формат, а для другого другой. 
Более логичным думается держать по LogModifier'у у каждого BaseLogger.
Плюс это даст возможность переопределить LogModifier каким нибудь потомком, чтобы например поменять цвет. Поменять код так, чтобы это было возможным будет куда проще если LogModifier не будет синглтоном

2020-04-20 00:03 UTC, ISkalchenkov commented on hw-2/CMakeLists.txt
> +include_directories(include)
Исправил, немного изменил структуру cmake

2020-04-20 00:03 UTC, ISkalchenkov commented on hw-2/include/FileLogger.hpp
> +    FileLogger(const FileLogger& rhs) = delete;
У basic_ofstream конструктор и оператор копирования удалены, поэтому эти методы у FileLogger'a будут неявно удалены

2020-04-20 00:05 UTC, ISkalchenkov commented on hw-2/include/FileLogger.hpp
> +    FileLogger(FileLogger&& rhs) = delete;
Понял, исправил

2020-04-20 00:05 UTC, ISkalchenkov commented on hw-2/src/Logger.cpp
> +    if (logger) {
Добавил

2020-04-20 00:06 UTC, ISkalchenkov commented on hw-2/src/LogModifier.cpp
> +std::string LogModifier::formate(const std::string msg, Level lvl) noexcept {
Исправлено

2020-04-20 00:06 UTC, ISkalchenkov commented on hw-2/include/LogModifier.hpp
> +    static LogModifier& get_instance() noexcept;
Спасибо, за объяснение. Исправил

2020-04-20 11:19 UTC, a-badin commented
Первая домашняя работа засчитана на 7

2020-04-20 11:20 UTC, a-badin approved these changes
Правьте конфликты и сливайте в мастер

2020-04-20 11:20 UTC, a-badin commented on hw-2/log/include/BaseLogger.hpp
> +    void debug(const std::string& msg) noexcept;
Не увлекайтесь noexcept, если конкретно сейчас ваш метод не кидает исключений, это не значит, что ему не потребуется кидать их потом. Тем более если класс предполагает наследование. Любому потомку может захотется пользоваться исключениями, которыми вы ему запретили пользоваться.

Например, если мы сделаем логгер, который отправляет лог на сервер. Тут точно могут быть ошибки соединения, тогда для warn и других методов нам придется или падать или игнорировать ошибки.

2020-04-22 00:03 UTC, merged