Hw-3
ISkalchenkov/AdvCpp.2020 pull request #3
Opened 2020-04-22 00:37 UTC by ISkalchenkov

2020-04-22 11:17 UTC, a-badin requested changes

2020-04-22 11:17 UTC, a-badin commented on hw-3/examples/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.15)
Это достаточно писать один раз в корневом CMakeLists.txt

2020-04-22 11:17 UTC, a-badin commented on hw-3/tcp/src/Socket.cpp
> +    this->fd_ = rhs.fd_;
Можно воспользоваться, если будет удобнее, std::exchange.
А вот вам задачка интересная. Как можно обменять значения у двух переменных без дополнительной памяти?

2020-04-22 11:17 UTC, a-badin commented on hw-3/tcp/src/Socket.cpp
> +    ::close(fd_);
В мане написано: "A careful programmer will check the return value of close()"

2020-04-22 11:17 UTC, a-badin commented on hw-3/tcp/src/Connection.cpp
> +    if (is_opened_) {
У вас идет путаница, получается что если read вернул 0 то сокет закрывать не нужно

2020-04-22 11:17 UTC, a-badin commented on hw-3/tcp/src/Connection.cpp
> +        is_opened_ = false;
is_opened != is_readable.

2020-04-22 11:17 UTC, a-badin commented on hw-3/tcp/src/Server.cpp
> +    if (is_opened_) {
Дублирует ли этот флаг логику?

2020-04-22 11:17 UTC, a-badin commented on hw-3/tcp/include/Exception.hpp
> +class SocketError : public std::exception {
Сделайте один общий предок тогда вам не придется писать:
```
 catch (const tcp::SocketError& err) {
        std::cout << err.what() << std::endl;
    }
    catch (const tcp::AddressError& err) {
        std::cout << err.what() << std::endl;
    }
```

2020-04-22 19:01 UTC, ISkalchenkov commented on hw-3/tcp/src/Socket.cpp
> +    this->fd_ = rhs.fd_;
Да, std::exchange удобнее, спасибо, исправил. Насчет задачки: чтобы обменять значения можно использовать побитовые операции(xor):
a = a ^ b;
b = b ^ a;
a = a ^ b;

2020-04-22 19:01 UTC, ISkalchenkov commented on hw-3/examples/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.15)
Понял, удалил

2020-04-22 19:02 UTC, ISkalchenkov commented on hw-3/tcp/src/Socket.cpp
> +    ::close(fd_);
Исправил

2020-04-22 19:03 UTC, ISkalchenkov commented on hw-3/tcp/src/Connection.cpp
> +    if (is_opened_) {
Исправил, теперь бросаю исключение

2020-04-22 19:06 UTC, ISkalchenkov commented on hw-3/tcp/src/Server.cpp
> +    if (is_opened_) {
Да, это было излишне. Удалось убрать флаги из Connection и Server

2020-04-22 19:06 UTC, ISkalchenkov commented on hw-3/tcp/include/Exception.hpp
> +class SocketError : public std::exception {
Сделано

2020-04-25 10:13 UTC, a-badin approved these changes

2020-04-25 10:13 UTC, a-badin commented on hw-3/tcp/src/Socket.cpp
> +        throw SocketError("Error closing socket: ");
Если почитать man close, то там описывается, что ядро сначала освободит вам дескриптор. То есть даже если возникнет ошибка, ваш дескриптор будет закрыт, и нужно выставить его в -1, чтобы не начать работать с чужим дескриптором. С EINT там вообще сложная ситуация, просто имейте это в виду, если будете программировать ядерную ракету или танк.

2020-04-25 10:13 UTC, merged