Hw-4
ISkalchenkov/AdvCpp.2020 pull request #4
Opened 2020-04-29 01:48 UTC by ISkalchenkov

2020-05-14 08:48 UTC, a-badin requested changes

2020-05-14 08:48 UTC, a-badin commented on hw-4/epoll_server/include/Connection.hpp
> +    Connection(int fd, int epoll_fd, const sockaddr_in& client_addr);
У вас нарушается Single Responsibility. Connection работает и с соединением и с epoll. Лучше вынести всю логику по работе с epoll в отдельный класс. set_event и get_event к сожалению придется оставить только потому, что в handle можно передать только Connection, а вам нужно знать события.

2020-05-14 08:48 UTC, a-badin commented on hw-4/epoll_server/src/Connection.cpp
> +Connection::Connection(int fd, int epoll_fd, const sockaddr_in& client_addr)
Вот этот epoll_fd очень смущает. Не понятно владеющий он или нет. Лучше просто подписать epoll на Connection где-то сверху

2020-05-14 08:48 UTC, a-badin commented on hw-4/epoll_server/src/Connection.cpp
> +        input_data_ += std::string(static_cast<const char*>(data), bytes_read);
Это получается какой-то side-effect. Сигнатура описывает, что метод делает одно. А сам метод делает что-то еще и input_data_ может переполнится. Заведите отдельный метод

2020-05-14 08:48 UTC, a-badin commented on hw-4/epoll_server/include/Connection.hpp
> +    std::string input_data_;
Есть ощущение, что input_data_ невозмжно очистить. тогда он может переполниться

2020-05-14 08:48 UTC, a-badin commented on hw-4/epoll_server/src/Server.cpp
> +        for (int n = 0; n < nfds; n++) {
Скорее всего компилятор оптимизирует, но строго говоря ++n

2020-06-02 20:12 UTC, ISkalchenkov commented
Спасибо. Было интересно учиться у вас.

2020-06-02 20:12 UTC, closed without merging